url: http://csinva.github.io
baseurl: ""

# Site Settings
title: Chandan Singh
description: "Chandan Singh Homepage"
keywords: "Chandan, Singh, Computer Science"
collections:
 notes:
    name: Notes
    documentation: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers
    output: true
# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
    syntax_highlighter_opts:
      # Use existing pygments syntax highlighting css
      css_class: 'highlight'
exclude: ["Rakefile", "LICENSE", "readme.markdown"]